# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('type', models.CharField(choices=[('c', 'Commodity'), ('d', 'Data'), ('m', 'Manufactured'), ('r', 'Raw Material')], default='m', max_length=1)),
                ('grade', models.PositiveSmallIntegerField(choices=[(1, 'very common'), (2, 'common'), (3, 'normal'), (4, 'rare'), (5, 'very rare')], default=1)),
            ],
        ),
    ]
