# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moduletype',
            options={'ordering': ['name']},
        ),
    ]
