# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0002_auto_20160603_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
