# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('ships', '0002_auto_20160603_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('module_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ships.ModuleType')),
            ],
        ),
        migrations.CreateModel(
            name='BlueprintRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='engineers.Blueprint')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_for', to='resources.Resource')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('blueprints', models.ManyToManyField(to='engineers.Blueprint')),
            ],
        ),
    ]
