# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
