# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_auto_20160604_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='allegience',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Indipendent'), (1, 'Federation'), (2, 'Empire'), (3, 'Alliance')], default=0),
        ),
    ]
