# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0003_modulestatistic'),
        ('engineers', '0003_engineer_allegience_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain', models.BooleanField(default=True)),
                ('range_min', models.DecimalField(decimal_places=5, default=0.0, max_digits=7)),
                ('range_max', models.DecimalField(decimal_places=5, default=0.0, max_digits=7)),
            ],
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='grade',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5')]),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='blueprints',
            field=models.ManyToManyField(related_name='engineers', to='engineers.Blueprint'),
        ),
        migrations.AddField(
            model_name='blueprinteffect',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_effects', to='engineers.Blueprint'),
        ),
        migrations.AddField(
            model_name='blueprinteffect',
            name='statistic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ships.ModuleStatistic'),
        ),
    ]
